baseurl = "https://serakasia.com"
title = "Serak International Asia"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "About Us"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "Locations"
    identifier = "groups"
    url  = "/groups/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com/serakasia"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/serakasia"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Instagram"
    url = "https://www.instagram.com/serakasia/"
    pre = "<i class='fa fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:info@serakasia.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Serak Asia"
    defaultKeywords = ["serak", "silat", "martial arts"]
    defaultDescription = "Site developed by Cowham Interactive"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@serakasia.com"

    about_us = """<p>Pukulan Pentjak Silat Serak is an Indonesian martial art 
    developed by Pak Serak, who was severely disabled, yet one of the most esteemed
    martial artists of Indonesia in the 18th Century. We have received the art from
    the Dutch Indonesian family of the De Vries and De Thouars. Our lineage is 
    from Pendekar Victor I.C. De Thouars.</p><p>Serak International Asia is the SE 
    Asia regional body of Serak International and the VDT Academy under the 
    leadership and supervision of Maha Guru Horacio Rodriguez.</p>"""

    copyright = "Copyright (c) 2017, Serak International; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Serak International Asia HQ</strong>
        <br>73 Mootee 13, 
        <br>Moobaan Huai Khrai, Tambon Wawi,
        <br>Amphoe Mae Suai, Chiang Rai, 
        <br><strong>Thailand</strong> 57180
      </p>
      <p>Tel: +66 (0)96 358 2774
        <br>Email: <a href="mailto:info@serakasia.com">info@serakasia.com</a>
        <br>Facebook: <a href="https://www.facebook.com/serakasia/">https://www.facebook.com/serakasia/</a>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
    <span class="hidden-sm hidden-xs">
        Contact us on +66 96 358 2774 or info@serakasia.com.
    </span>
    <span class="hidden-md hidden-lg">
        <a href="#" data-animate-hover="pulse">
            <i class="fa fa-phone"></i>
        </a>
        <a href="#" data-animate-hover="pulse">
            <i class="fa fa-envelope"></i>
        </a>
    </span>
    """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Student Testimonials"
    subtitle = "In the Serak International family we encourage and cultivate a close family atmosphere where a spirit of brotherhood is highly valued. Read what some of our brothers have to say about their training experience with us."

[params.see_more]
    enable = true
    icon = "fa fa-calendar"
    title = "Upcoming Events, Camps & Seminars"
    subtitle = "Our next upcoming event is a Serak Camp with Maha Guru Horacio Rodriguqez in October 2018"
    link_url = "/events/2015"
    link_text = "Check out upcoming events"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Check out the latest news, announcements, articles, training tips, musings and other updated content on our blog."

